#!/usr/bin/env bash

if [ "$(pidof i3)" ]
then
      /usr/bin/termite -e 'ssh -o ServerAliveInterval=100 -t srsantos@ubuntu_server "mutt"' --class=mutt
  else
      /usr/bin/ssh -o ServerAliveInterval=100 -t srsantos@ubuntu_server "mutt"
fi
